kind: Deployment
apiVersion: apps/v1
metadata: 
  name: helloworld
  labels:
    app: helloworld
spec:
  template:
    metadata:
      name: helloworld-pod
      labels:
        app: helloworld
    spec:
      containers:
      - name: spring-hello-world
        image: iumehara/spring-hello-world:latest
        envFrom:
          - configMapRef:
              name: helloworld-config
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
 
