version: "3"

services:
  app:
    container_name: helloworld
    restart: always
    build: ./
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
    depends_on:
      - db

  db:
    container_name: helloworld_db
    restart: always
    build: ./src/main/resources/db
    expose:
      - "5432"
    volumes:
      - ./data:/data/db
    ports:
      - "5432"
